apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-app
  labels:
    app: fe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-app
  template:
    metadata:
      labels:
        app: fe-app
    spec:
      containers:
      - name: udagram-frontend
        image: nhattcd99/udagram-frontend:v2.0.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1m"
          requests:
            cpu: "1m"
